projectPath: ./packExport
expansionPath: .
buildFile: AllDataPacks.json
queries: 
  - OmniScript/License_ABF_English
  - OmniScript/SG Quoting_ABF_English

activate: true
compileOnBuild: true
maxDepth: 0
continueAfterError: true
defaultMaxParallel: 10
exportPacksMaxSize: 10
useAllRelationships: false
supportForceDeploy: true